### PR TITLE
Test against Node 0.12 and io.js

### PR DESCRIPTION
**Pull request by ilanbiala**

### CODE REVIEW

**Comment by ilanbiala** [comment]
@bunkat tests probably aren't passing because of a failed test, not io.js or 0.12.

**Comment by ilanbiala** [comment]
@bunkat can this be merged in?

**Comment by ilanbiala** [comment]
@bunkat any issue with this PR?

**Comment by ilanbiala** [comment]
@bunkat can we get this merged in? Testing against 0.12 is pretty important now that it's a real release.

**Comment by ilanbiala** [comment]
@bunkat any issue with merging this?

**Comment by ilanbiala** [comment]
@bunkat can we get this merged in and released in a new npm version? This PR has been sitting around and I think a lot of people could use it.

**Comment by ilanbiala** [comment]
@bunkat still waiting on this. Can you merge it in?

**Comment by ilanbiala** [comment]
@bunkat you also have to test against Node 4 and 5 now.

**Comment by bunkat** [comment]
Updated to test against 0.10 and latest which should be sufficient.

**Pull request closed without merging**
