### PR TITLE
separate logic for understanding cron syntax and parsing cron syntax

### LINKED ISSUE #44: cron parsing: ignore multipel whitespaces, tab
From `man 5 corntab`
> "The fields may be separated by **spaces** or **tabs**."

A simple regex-replace would do the trick

```
replace(/(\s)+/g, ' ');
```

### PR DESCRIPTION
**Pull request by philjc**
fixes #44

### CODE REVIEW

**Comment by ilanbiala** [comment]
@philjc can you get tests passing and then @bunkat can revisit this PR?

**Comment by philjc** [comment]
Will do, later this week.

**Comment by philjc** [comment]
@ilanbiala I've run the tests locally, there are no failing tests. For whatever reason the Travis CI build seems to be running in verbose mode so it's generate a lot of output which gives us the following error (*The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).*)

**Comment by ilanbiala** [comment]
@bunkat are you going to merge this in? @philjc says there are no failing tests when running locally, which means Travis probably can't handle all the assertions being printed out.

**Pull request closed without merging**
